definition:
#show = Show something
#bounce = A vertical movement
#pop = A sudden appearance
#slide = A horizontal movement
#slump = lower the character in y axis
#creeped = slide the character slowly to the side
#pos_left = Position the character to the left
#pos_right = Position the character to the right
#pos_center = Position the character in the middle
#n = Neutral face
#a = Angry face
#am = amazed face
#s = Sad face
#se = serious face
#sc = scared face
#sm = smug face
#sur = Surprised face
#c = Concerned face
#cr = creeped face
#q = questioning face
#d = dissapointed face
#h = happy face
#e = excited face
#bglab = Background Lab
#bghs = Background Hillside
#bgCHAR1 = Background game CHAR 1
#bgCHAR2 = Background game CHAR 2
#bgCHAR3 = Background game CHAR 3
#bgCHAR4 = Background gmae CHAR 4
#bgbe = Background BAD END
#bgb = Background BLACK SCREEN
#bgd = Darkened version of the background
#bghe = Background Healthy Earth
#bgff = Background Flourishing forest
#bgfz = Background Family Goint to the Zoo
#bgmc = Background Magazine with the player on it